"""Static gates that keep the dead-code cleanup from silently undoing itself.

The Cleaning_day pass removed 125 unused imports, 25 uncalled functions and a
duplicate class definition. Without a gate, that debt grows straight back. These
tests are the ratchet.

They need flake8, which is a development dependency rather than a runtime one,
so the whole module skips if it is not installed (`pip install -r
requirements-dev.txt`).
"""

from __future__ import annotations

import ast
import pathlib
import subprocess
import sys

import pytest

pytestmark = pytest.mark.hygiene

flake8 = pytest.importorskip("flake8", reason="pip install -r requirements-dev.txt")

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent

#: Checked directories. "Scanner App V1" is a frozen PyInstaller build with a
#: vendored copy of cv2 and PySide6 -- a build artifact, not source.
CHECKED_PATHS = ["scanner", "gui", "tests"]

#: Auto-generated by pyside6-uic. Their unused imports come back on every
#: regeneration, so hand-editing them is pointless; fix it in the .ui workflow.
GENERATED_FILES = {
    "gui/ui_scanner.py",
    "gui/ui_scanner_plotter_version.py",
}

#: F401 unused import, F811 redefinition, F841 unused local. The three findings
#: the cleanup drove to zero.
DEAD_CODE_CHECKS = "F401,F811,F841"


def run_flake8(select: str, paths: list[str]) -> list[str]:
    result = subprocess.run(
        [sys.executable, "-m", "flake8", f"--select={select}", *paths],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    return [
        line
        for line in result.stdout.splitlines()
        if line.strip()
        and not any(line.startswith(f"./{g}") or line.startswith(g) for g in GENERATED_FILES)
    ]


class TestNoDeadCodeRegressions:
    def test_no_unused_imports_or_locals(self):
        """The gate. Adding an unused import fails the build.

        If a finding is a false positive -- a module imported purely for a
        registration side effect, say -- mark that one line `# noqa: F401`
        rather than loosening this test.
        """
        findings = run_flake8(DEAD_CODE_CHECKS, CHECKED_PATHS)
        assert not findings, (
            "dead code has come back:\n  " + "\n  ".join(findings)
        )

    def test_the_root_level_scripts_are_clean_too(self):
        root_scripts = [
            p.name for p in REPO_ROOT.glob("*.py") if p.name != "setup.py"
        ]
        findings = run_flake8(DEAD_CODE_CHECKS, root_scripts)
        assert not findings, (
            "dead code has come back:\n  " + "\n  ".join(findings)
        )

    def test_the_generated_ui_exclusion_list_is_accurate(self):
        """If a generated file is deleted or renamed, stop excluding it."""
        for name in GENERATED_FILES:
            assert (REPO_ROOT / name).is_file(), f"{name} no longer exists"

    def test_the_excluded_files_really_are_generated(self):
        """Guards against someone parking hand-written code on the exemption."""
        for name in GENERATED_FILES:
            head = (REPO_ROOT / name).read_text(encoding="utf-8")[:1000]
            assert "Qt User Interface Compiler" in head, (
                f"{name} is on the generated-file exemption but does not carry "
                "the uic banner"
            )


class TestNoUndefinedNames:
    def test_no_new_undefined_names(self):
        """F821 catches a name that was deleted while a reference survived.

        `scanner/scanner.py` has six pre-existing F821 hits for
        `all_s_params_data`, present on master and documented in
        DEAD_CODE_REPORT.txt section 3.7. They are allow-listed here so the
        gate is useful today; fix them and this test tightens automatically.
        """
        findings = run_flake8("F821", CHECKED_PATHS + ["test_scanner_gui.py"])
        unexpected = [f for f in findings if "all_s_params_data" not in f]
        assert not unexpected, (
            "a reference to a name that does not exist:\n  "
            + "\n  ".join(unexpected)
        )

    def test_the_known_undefined_name_count_has_not_grown(self):
        findings = run_flake8("F821", CHECKED_PATHS)
        known = [f for f in findings if "all_s_params_data" in f]
        assert len(known) <= 6, (
            f"the pre-existing all_s_params_data defect has spread to "
            f"{len(known)} sites (was 6). See DEAD_CODE_REPORT.txt section 3.7."
        )


class TestNoDuplicateDefinitions:
    """A class or function defined twice in one module silently shadows itself.

    This is what hid the duplicate `AxisInsn` in geckoInstructions.py: ten
    subclasses bound to the second definition while the first sat there looking
    load-bearing.
    """

    @staticmethod
    def duplicate_top_level_names(path: pathlib.Path) -> list[str]:
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError:
            return []

        seen: dict[str, int] = {}
        for node in tree.body:
            if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
                seen[node.name] = seen.get(node.name, 0) + 1
        return sorted(name for name, count in seen.items() if count > 1)

    def source_files(self) -> list[pathlib.Path]:
        files: list[pathlib.Path] = []
        for directory in CHECKED_PATHS:
            files.extend((REPO_ROOT / directory).rglob("*.py"))
        files.extend(REPO_ROOT.glob("*.py"))
        return sorted(
            f
            for f in files
            if str(f.relative_to(REPO_ROOT)).replace("\\", "/") not in GENERATED_FILES
        )

    def test_no_module_defines_the_same_name_twice(self):
        offenders = {}
        for path in self.source_files():
            duplicates = self.duplicate_top_level_names(path)
            if duplicates:
                offenders[str(path.relative_to(REPO_ROOT))] = duplicates

        assert not offenders, (
            "a name is defined more than once at module scope, so the first "
            f"definition is dead and shadowed: {offenders}"
        )

    # Duplicate *methods* inside a class are deliberately not checked here.
    # flake8's F811 already covers that case and does it better: it understands
    # that `@property` + `@value.setter` legitimately bind the same name twice,
    # which a plain AST count cannot tell apart from a genuine shadowing. The
    # F401/F811/F841 gate above is what guards method-level redefinition.


class TestNoUnreachableCode:
    """Statements after an unconditional return/raise/break/continue."""

    @staticmethod
    def unreachable_in(path: pathlib.Path) -> list[int]:
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError:
            return []

        terminators = (ast.Return, ast.Raise, ast.Break, ast.Continue)
        found: list[int] = []

        def walk(body):
            for index, node in enumerate(body):
                if isinstance(node, terminators) and index < len(body) - 1:
                    found.append(body[index + 1].lineno)
            for node in body:
                for field in ("body", "orelse", "finalbody"):
                    inner = getattr(node, field, None)
                    if isinstance(inner, list) and inner and isinstance(inner[0], ast.stmt):
                        walk(inner)
                for handler in getattr(node, "handlers", []) or []:
                    walk(handler.body)

        walk(tree.body)
        return found

    def test_nothing_is_stranded_after_a_return_or_raise(self):
        offenders = {}
        for directory in CHECKED_PATHS:
            for path in (REPO_ROOT / directory).rglob("*.py"):
                if str(path.relative_to(REPO_ROOT)).replace("\\", "/") in GENERATED_FILES:
                    continue
                lines = self.unreachable_in(path)
                if lines:
                    offenders[str(path.relative_to(REPO_ROOT))] = lines

        assert not offenders, f"unreachable statements: {offenders}"
